---
apiVersion: v1
kind: ConfigMap
metadata:
  name: packetbeat-init-config
  namespace: kube-system
  labels:
    k8s-app: packetbeat-init
data:
  packetbeat.yml: |-
    setup.template.settings:
      index.mapping.total_fields.limit: 10000

    packetbeat.interfaces.device: any

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: packetbeat-init
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: packetbeat-init
        image: docker.elastic.co/beats/packetbeat:7.12.0
        args: [
          "-c", "/etc/packetbeat.yml",
          "-e",
          "setup"
        ]
        env:
        - name: ELASTIC_CLOUD_ID
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-id
        - name: ELASTIC_CLOUD_AUTH
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-auth
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: /etc/packetbeat.yml
          readOnly: true
          subPath: packetbeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: packetbeat-init-config
      restartPolicy: Never
  backoffLimit: 0
