---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat-synthetics
  labels:
    app: heartbeat-synthetics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeat-synthetics
  template:
    metadata:
      labels:
        app: heartbeat-synthetics
    spec:
      containers:
      - name: heartbeat-synthetics
        image: docker.elastic.co/beats/heartbeat:7.12.0
        args: [
          "-c", "/usr/share/heartbeat/heartbeat.yml",
          "-e"
        ]
        env:
        - name: ELASTIC_CLOUD_ID
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-id
        - name: ELASTIC_CLOUD_AUTH
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-auth
        volumeMounts:
        - name: defaultconf
          mountPath: /usr/share/heartbeat/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
      volumes:
      - name: defaultconf
        configMap:
          name: heartbeat-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  labels:
    k8s-app: heartbeat-synthetics
data:
  heartbeat.yml: |-
    seccomp.enabled: false

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    processors:

    heartbeat.monitors:

    - type: browser
      id: home2edit-monitor
      name: Home -> Edit Owner journey
      schedule: "@every 1s"
      source:
        inline:
          script: |-
            step("load homepage", async () => {
                await page.goto('http://petclinic-nginx-service/');
                await page.waitForRequest(/intake/);
            });
            step("click on find owners", async () => {
                await page.click('#main-navbar > ul > li:nth-child(3) > a');
                await page.waitForRequest(/intake/);
            });
            step("click on find owners button", async () => {
                await page.click('#search-owner-form > div:nth-child(2) > div > button');
                await page.waitForRequest(/intake/);
            });
            step("click on Eduardo Rodriguez", async () => {
                await page.click('#vets > tbody > tr:nth-child(3) > td:nth-child(1) > a');
                await page.waitForRequest(/intake/);
            });
            step("click on edit owner button", async () => {
                await page.click('body > div.container-fluid > div > a:nth-child(3)');
                await page.waitForRequest(/intake/);
            });

    - type: browser
      id: home2vets-monitor
      name: Home -> Show Vets journey
      schedule: "@every 1s"
      source:
        inline:
          script: |-
            step("load homepage", async () => {
                await page.goto('http://petclinic-nginx-service/');
                await page.waitForRequest(/intake/);
            });
            step("click on vets", async () => {
                await page.click('#main-navbar > ul > li:nth-child(4) > a');
                await page.waitForRequest(/intake/);
            });

    - type: browser
      id: home2addpet-monitor
      name: Home -> Add Owner journey
      schedule: "@every 1s"
      source:
        inline:
          script: |-
            step("load homepage", async () => {
                await page.goto('http://petclinic-nginx-service/');
                await page.waitForRequest(/intake/);
            });
            step("click on find owners", async () => {
                await page.click('#main-navbar > ul > li:nth-child(3) > a');
                await page.waitForRequest(/intake/);
            });
            step("click on add Owner button", async () => {
                await page.click('body > div.container-fluid > div > a');
                await page.waitForRequest(/intake/);
            });

    - type: browser
      id: error-monitor
      name: Home -> Error journey
      schedule: "@every 6s"
      source:
        inline:
          script: |-
            step("load homepage", async () => {
                await page.goto('http://petclinic-nginx-service/');
                await page.waitForRequest(/intake/);
            });
            step("click on error", async () => {
                await page.click('#main-navbar > ul > li:nth-child(5) > a');
                await page.waitForRequest(/intake/);
            });
