apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    co.elastic.monitor/name: mysql-tcp-svc
    co.elastic.monitor/type: tcp
    co.elastic.monitor/hosts: mysql-service.default.svc.cluster.local:3306
    co.elastic.monitor/schedule: "@every 5s"
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        co.elastic.logs/module: mysql

        co.elastic.metrics/module: mysql
        co.elastic.metrics/hosts: 'root:petclinic@tcp(${data.host}:${data.port})/'

    spec:
      containers:
      - name: mysql
        image: mysql:5.7.27
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: 400Mi
          requests:
            memory: 300Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: petclinic
        - name: MYSQL_DATABASE
          value: petclinic
